{"name": "test_add[except]", "status": "failed", "statusDetails": {"message": "AssertionError: assert None == '请输入数字'", "trace": "self = <test_calculator2.test_calc.TestCalc object at 0x102ddbca0>, get_calc = <code.calculator.Calculator object at 0x102daf760>\nget_datas_add = ['', 5, '请输入数字']\n\n    @pytest.mark.run(order=1)\n    def test_add(self, get_calc, get_datas_add):\n        result = None\n        try:\n            # 调用add函数,返回的结果保存在result里面\n            result = get_calc.add(get_datas_add[0], get_datas_add[1])\n            # 判断result结果是否等于期望的值\n            if isinstance(result, float):\n                result = round(result, 2)\n        except Exception as e:\n            print(e)\n>       assert result == get_datas_add[2]\nE       AssertionError: assert None == '请输入数字'\n\ntest_calc.py:23: AssertionError"}, "attachments": [{"name": "stdout", "source": "081e0ba6-4381-4cab-b057-d699523a84f8-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "get_datas_add", "value": "['', 5, '请输入数字']"}], "start": 1609828829845, "stop": 1609828829845, "uuid": "d8c83b48-ef3f-477b-ac9c-648618ee5659", "historyId": "091dd209a3495e40179dfe387a2fc1c5", "testCaseId": "a7b29b08300809261dc069b49da8543b", "fullName": "test_calc.TestCalc#test_add", "labels": [{"name": "tag", "value": "run(order=1)"}, {"name": "suite", "value": "test_calc"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "yunboshengs-MacBook-Pro.local"}, {"name": "thread", "value": "13270-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calc"}]}