{"name": "test_mul[except]", "status": "failed", "statusDetails": {"message": "AssertionError: assert '' == '请输入数字'\n  - 请输入数字", "trace": "self = <test_calculator2.test_calc.TestCalc object at 0x102ddb760>, get_calc = <code.calculator.Calculator object at 0x102daf760>\nget_datas_mul = ['', 5, '请输入数字']\n\n    @pytest.mark.run(order=3)\n    def test_mul(self, get_calc, get_datas_mul):\n        result = None\n        try:\n            # 调用add函数,返回的结果保存在result里面\n            result = get_calc.mul(get_datas_mul[0], get_datas_mul[1])\n            # 判断result结果是否等于期望的值\n            if isinstance(result, float):\n                result = round(result, 2)\n        except Exception as e:\n            print(e)\n>       assert result == get_datas_mul[2]\nE       AssertionError: assert '' == '请输入数字'\nE         - 请输入数字\n\ntest_calc.py:62: AssertionError"}, "attachments": [{"name": "stdout", "source": "0bd7ac86-dbb6-473c-9cd2-97190e2ebd51-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "get_datas_mul", "value": "['', 5, '请输入数字']"}], "start": 1609828829905, "stop": 1609828829906, "uuid": "1a7c0904-1c4b-4617-a018-ebe989ac620f", "historyId": "5aaee5843b34a6d22ef39662ec372c60", "testCaseId": "463eb02829151a13063664521f3c4534", "fullName": "test_calc.TestCalc#test_mul", "labels": [{"name": "tag", "value": "run(order=3)"}, {"name": "suite", "value": "test_calc"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "yunboshengs-MacBook-Pro.local"}, {"name": "thread", "value": "13270-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calc"}]}