{"name": "test_div[except]", "status": "failed", "statusDetails": {"message": "AssertionError: assert None == '请输入数字'", "trace": "self = <test_calculator2.test_calc.TestCalc object at 0x102e22b20>, get_calc = <code.calculator.Calculator object at 0x102daf760>\nget_datas_div = ['', 5, '请输入数字']\n\n    @pytest.mark.run(order=4)\n    def test_div(self, get_calc, get_datas_div):\n        result = None\n        try:\n            # 调用add函数,返回的结果保存在result里面\n            result = get_calc.div(get_datas_div[0], get_datas_div[1])\n            # 判断result结果是否等于期望的值\n            if isinstance(result, float):\n                result = round(result, 2)\n        except Exception as e:\n            print(e)\n>       assert result == get_datas_div[2]\nE       AssertionError: assert None == '请输入数字'\n\ntest_calc.py:36: AssertionError"}, "attachments": [{"name": "stdout", "source": "2078b921-d560-494e-b90f-5cb3f1869f13-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "get_datas_div", "value": "['', 5, '请输入数字']"}], "start": 1609828829921, "stop": 1609828829921, "uuid": "9a76a15e-715d-440b-b196-547ce25ccb21", "historyId": "156b97367a65664a4b884d31709784d6", "testCaseId": "4a57f615ae930c12d705a9fc7a66b88d", "fullName": "test_calc.TestCalc#test_div", "labels": [{"name": "tag", "value": "run(order=4)"}, {"name": "suite", "value": "test_calc"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "yunboshengs-MacBook-Pro.local"}, {"name": "thread", "value": "13270-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calc"}]}